// .github/workflows/expo.yml

name: Build and Test OmniGPT Mobile App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests (if any)
        run: echo "No tests defined yet. Add tests for CI."

      - name: Expo publish check
        run: npx expo install && npx expo doctor
